### ISSUE TITLE
False positive for yelling

### ISSUE THREAD

**Issue by kotp** [yyyc514/exercism_plus#2]
When referencing the `README.md` file even in backticks, we get a false positive for yelling.

**Comment by yyyc514** [comment]
Yeah because the ContentParser does nothing yet but pass the whole content straight thru.  thanks for filing issue.

**Comment by yyyc514** [comment]
It needs to:

- [ ] filter out code blocks (long form and short)
- [ ] filter out prior quoted text (from the student or mentor)

**Comment by yyyc514** [comment]
Closed by https://github.com/yyyc514/exercism_plus/commit/527fb741568b507abf40b1d8f341c219f9a4cb19
